---
 - hosts: servers
   become: true
   tasks: 
   
     - name: ntp install
       yum: name=ntp state=latest
   
     - name: copy ntp config file
       copy:
         src: ntp.conf 
         dest: /etc/ntp.conf
       notify:
        - restart ntp
         
   handlers:
     - name: restart ntp
       service: name=ntpd state=restarted 
